### ISSUE TITLE
Explain the utility of the routes.js file

### ISSUE THREAD

**Issue by redixhumayun** [MunupatrulaSiddharth/idflo-assignment-js-node#1]
You have a file called routes.js in your node repo, where you have some routes that don't make sense. Please explain the utility of that file.

**Comment by MunupatrulaSiddharth** [comment]
Oops ! I was working on things in parallel yesterday. I had been looking into them in a single file for writing my APIs. Forgot to delete before pushing. Apologies.

Made the changes and pushed it.
